# Generated by Django 5.1.2 on 2024-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylequizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='asd', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='uuid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
