# Generated by Django 5.1.2 on 2024-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylequizz', '0004_alter_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
