# Generated by Django 5.1.2 on 2024-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylequizz', '0007_alter_examscore_score_alter_examscore_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='discouser',
            name='guild_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examscore',
            name='guild_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
